Fix running openjdk11 compilation on openjdk8
Seemingly, the openjdk11 compiler optimizes the call to
java.nio.Buffer.flip() in to be directly on the java.nio.ByteBuffer
type.  We fixed other instances of java.nio.Buffer interfaces to the
point of being able to run the ANSI-TEST suite.


This caused errors such as:

      Exception in thread "interpreter" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
      at org.armedbear.lisp.util.DecodingReader.<init>(DecodingReader.java:87)
      at org.armedbear.lisp.Stream.<init>(Stream.java:165)
      at org.armedbear.lisp.Stream.<init>(Stream.java:148)